version: "3.8"

services:

  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"

  server:
    build: ./server
    container_name: node_server
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/mydb

  client:
    build: ./client
    container_name: react_client
    ports:
      - "5173:5173"
    depends_on:
      - server